# Generated by Selenium IDE
import time
import json
import ast
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from webdriver_manager.chrome import ChromeDriverManager
class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_booking1(self):
    # Test name: booking1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://warrior.uwaterloo.ca/")
    
    
    # setup cookies
    with open('cookie.txt') as f:
      d = f.read()
      data = ast.literal_eval(d)
      for l in data:
        self.driver.add_cookie(l)
 
    # self.driver.add_cookie({'domain': 'warrior.uwaterloo.ca', 'httpOnly': True, 'name': '.AspNet.ApplicationCookie', 'path': '/', 'secure': True, 'value': '3tHL3_hJKQDnV0VSQHIBU6xN96F74K9V2n7f9FsKIi2RB7kW41pxxFsJT7Mm2fHZtgHgg6TI4d2djiaxZ_Fzgj1MAioqTLNAOBnHKh1SwYKFWm-hmw0HxbJlVT-C35rW7VGpVTl2H7l66rLNSs6VXSo6vh-n6zcTW3KIgkXNHd770kIiXZko_XCKi-NKi9Wqs0PTzeTSfCiurGKR5GwEHDs3t_T9vEFzlcLqA4Uf1IfxsCatpWF9rTZKEjl1bokfqrpn2mewxNW96dDGkaEUX8KBevbsGrRInv0B0TfRpQO958e3UTqx5wB8DYXxQJVD9SJB_fVDL5JzZoSgp_MuHfYzDmCSur4axdTXwDg1dKCpot24fu_Myd7mXROtw-IW'})
    # self.driver.add_cookie({'domain': 'warrior.uwaterloo.ca', 'httpOnly': True, 'name': '_shibsession_64656661756c7468747470733a2f2f77617272696f722e7577617465726c6f6f2e63612f73686962626f6c657468', 'path': '/', 'secure': True, 'value': '_e65c97d8781d0953fe7d209f51869ad4'})
    # self.driver.add_cookie({'domain': '.uwaterloo.ca', 'expiry': 1614624038, 'httpOnly': False, 'name': '_gat', 'path': '/', 'secure': False, 'value': '1'})
    # self.driver.add_cookie({'domain': '.uwaterloo.ca', 'expiry': 1677695999, 'httpOnly': False, 'name': '_ga', 'path': '/', 'secure': False, 'value': 'GA1.2.1396064240.1614623979'})
    # self.driver.add_cookie({'domain': 'warrior.uwaterloo.ca', 'httpOnly': True, 'name': '__RequestVerificationToken', 'path': '/', 'secure': True, 'value': 'mhdlxSySlQ_H6kahXJ782xksY0-dV1trBiK78fxy4FYYYIhv6as06V2BP_2SouGv4s7eSe1jS9VuFMoCMpyMmd6HYWPGivvLfp3x5mNupx81'})
    # self.driver.add_cookie({'domain': '.uwaterloo.ca', 'expiry': 1614710399, 'httpOnly': False, 'name': '_gid', 'path': '/', 'secure': False, 'value': 'GA1.2.1965586508.1614623979'})
    # self.driver.add_cookie({'domain': 'warrior.uwaterloo.ca', 'httpOnly': True, 'name': 'ASP.NET_SessionId', 'path': '/', 'sameSite': 'Lax', 'secure': True, 'value': '3101nnpbz1zvt2pdxgsn0aft'})
    # self.driver.add_cookie({"name": "key", "value": "value"})
    
    # 2 | setWindowSize | 1920x1050 | 
    self.driver.set_window_size(1920, 1050)
    
    self.driver.find_element_by_id('loginLink').click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".btn-soundcloud")))
    self.driver.find_element(By.CSS_SELECTOR, ".btn-soundcloud").click()
    # 3 | waitForElementPresent | css=.col-lg-3:nth-child(1) .img-responsive | 30000
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".col-lg-3:nth-child(1) .img-responsive")))
    # # 4 | click | css=.col-lg-3:nth-child(1) .img-responsive | 
    # self.driver.find_element(By.CSS_SELECTOR, ".col-lg-3:nth-child(1) .img-responsive").click()
    # # 5 | click | css=.list-group-item:nth-child(3) .img-thumbnail | 
    # self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(3) .img-thumbnail").click()
    self.driver.get('https://warrior.uwaterloo.ca/Program/GetProgramDetails?courseId=cc2a16d7-f148-461e-831d-7d4659726dd1&semesterId=26de9ca7-b227-429c-b21f-633b4cb4c462')
    # 6 | click | css=div:nth-child(4) > .btn-primary | 
    while True:
      try:
        #code with possible error
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > .btn-primary").click()
      except:
        self.driver.get('https://warrior.uwaterloo.ca/Program/GetProgramDetails?courseId=cc2a16d7-f148-461e-831d-7d4659726dd1&semesterId=26de9ca7-b227-429c-b21f-633b4cb4c462')
        continue
      else:
        #the rest of the code
        break
    # 7 | click | id=btnAccept | 
    self.driver.find_element(By.ID, "btnAccept").click()
    # 8 | click | id=rbtnNo | 
    self.driver.find_element(By.ID, "rbtnNo").click()
    # 9 | click | css=.panel:nth-child(21) > .panel-body | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(21) > .panel-body").click()
    # 10 | click | css=.panel:nth-child(21) #rbtnNo | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(21) #rbtnNo").click()
    # 11 | click | css=.panel:nth-child(27) .radio-inline:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(27) .radio-inline:nth-child(3)").click()
    # 12 | click | css=.panel:nth-child(33) #rbtnNo | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(33) #rbtnNo").click()
    # 13 | click | css=.panel:nth-child(39) .radio-inline:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(39) .radio-inline:nth-child(3)").click()
    # 14 | click | css=.panel:nth-child(45) > .panel-body | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(45) > .panel-body").click()
    # 15 | click | css=.panel:nth-child(45) > .panel-body | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(45) > .panel-body").click()
    # 16 | click | css=.panel:nth-child(45) .radio-inline:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(45) .radio-inline:nth-child(3)").click()
    # 17 | click | css=.panel:nth-child(51) .radio-inline:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(51) .radio-inline:nth-child(3)").click()
    # 18 | click | css=.panel:nth-child(57) .radio-inline:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(57) .radio-inline:nth-child(3)").click()
    # 19 | click | css=.panel:nth-child(63) .radio-inline:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel:nth-child(63) .radio-inline:nth-child(3)").click()
    # 20 | click | css=.container-fluid > .btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".container-fluid > .btn-primary").click()
  
t = TestDefaultSuite()
t.setup_method(None)
t.test_booking1()
t.teardown_method(None)